CREATE TABLE [dbo].[Images]
(
	[ID] UNIQUEIDENTIFIER NOT NULL CONSTRAINT [PK_Images] PRIMARY KEY,
    [FileExtension] NVARCHAR(16) NOT NULL,
    CONSTRAINT [FK_Images_Sections] FOREIGN KEY ([ID]) REFERENCES [Sections] ([ID])
)
