CREATE TABLE [dbo].[ListItems]
(
	[ID] UNIQUEIDENTIFIER NOT NULL CONSTRAINT [PK_ListItems] PRIMARY KEY,
    [Text] NVARCHAR(1024) NOT NULL,
    CONSTRAINT [FK_ListItems_Sections] FOREIGN KEY ([ID]) REFERENCES [Sections] ([ID])
)
